### ISSUE TITLE
about atomic mode setting

### ISSUE THREAD

**Issue by ds-hwang** [dvdhrm/docs#1]
Hi @dvdhrm,

This project was my life saver when I started my gbm project. Would you happen to have plan to catch up latest atomic mode setting API. drmModeAtomicCommit

Best, DS

**Comment by peewe** [comment]
Hey @dvdhrm,
I'm try to run this amazing project and my output is :
```
root@MY-VirtualBox:/home/MY/Desktop/docs-master/drm-howto# ./modeset-vsyncusing card '/dev/dri/card0'
mode for connector 26 is 1920x1080
cannot set CRTC for connector 26 (13): Permission denied
cannot flip CRTC for connector 26 (13): Permission denied
wait for pending page-flip to complete...
exiting

```
I wonder if there is a way to make it work on the new screens we have today ( not only on CRTC ).
Thank you for sharing your knowledge!

**Comment by athul7pk** [comment]
**I tried to change modeset_draw to display R,G,B values dynamically as shown ...

but it is showing the inintial color itself any Idea?**
How to commit or buffer (or page flip needed?)

_
----------------------------------------------------------------------------------------------
static void modeset_draw(void)
{
	uint8_t r, g, b;
	bool r_up, g_up, b_up;
	unsigned int i, j, k, off;
	struct modeset_dev *iter;

	srand(time(NULL));
	r = rand() % 0xff;
	g = rand() % 0xff;
	b = rand() % 0xff;
	r_up = g_up = b_up = true;
	uint32_t ccc[]={0x7fff0000,0x7f00ff00,0x7f0000ff,0x7fff00ff,0x7fffff00};
	for (i = 0; i < 50; ++i) {
/*		r = next_color(&r_up, r, 20);
		g = next_color(&g_up, g, 10);
		b = next_color(&b_up, b, 5);
*/
		for (iter = modeset_list; iter; iter = iter->next) {
			for (j = 0; j < iter->height; ++j) {
				for (k = 0; k < iter->width; ++k) {
					off = iter->stride * j + k * 4;
					*(uint32_t*)&iter->map[off] =ccc[i%4];
						   //  (r << 16) | (g << 8) | b;
				}
			}
		}
printf("setting %x \r\n",ccc[i]);
		usleep(1000000);
	}
}

_

**Comment by leandrohrb** [comment]
I think that this issue can be closed, as now there is an example explaining the atomic API.

**Comment by dvdhrm** [comment]
Right! Thanks!
