### ISSUE TITLE
How to set correct colorspace (RGB/BGR/etc.)?

### ISSUE THREAD

**Issue by MLXProjects** [dvdhrm/docs#14]
I'm using the drmModeAddFB() call which requests to add the framebuffer using RGB as the default pixel format, which for some displays seem to be wrong (red and blue are inverted because of the display using BGR colorspace).
Can the correct display colorspace be detected in some way?
IIRC the encoder should take care of adapting the pixel data properly, but for some reason that doesn't happen here...

**Comment by dvdhrm** [comment]
Use `drmModeAddFB2()` (see modeset-atomic.c for an example). This call allows specifying the encoding (well, also the color-space in a sense, but not exactly, since sRGB and friends need further configuration).

**Comment by MLXProjects** [comment]
> This call allows specifying the encoding (well, also the color-space in a sense, but not exactly, since sRGB and friends need further configuration).

The issue is that I don't always know the correct encoding/colorspace beforehand, the idea is to find it out using any other drm api if it exists
For example, using fbdev, you could know it by checking the red/green/blue offsets

**Comment by dvdhrm** [comment]
I think the idea is that you specify which one to use and the hardware adapts, not the other way around. However, there is likely a way to query the crtc/encoders for the supported four-cc codes, but I am currently not sure about it. I recommend checking what the existing compositors do and how they decide what to use as argument to `drmModeAddFB2`.

**Comment by MLXProjects** [comment]
Thanks! I'll close the issue so it doesn't keep around, and will research the reason of this not working as I think it should.
I'll post back if I ever find the correct way of doing this.
