### ISSUE TITLE
How to know the supported color formats

### ISSUE THREAD

**Issue by malfer** [dvdhrm/docs#15]
Thanks to these example programs I have been able to add a simple DRM driver to my small 2D graphics library MGRX and it works. But the examples assume a 32 bit XRGB color format instead of searching for supported color formats, indeed there is another issue here that was resolved changing the color format to a 24 or 16 bit format. Is there a way to pre-know the supported color formats for every mode?

**Comment by dvdhrm** [comment]
The examples use `dumb-buffers`, which is the driver-agnostic way to drive the display. For those, I think nearly everyone assumes 32bit RGBX buffers are supported (I even thought that was a requirement to support the dumb-buffer-API).

I would assume that the supported color-formats are fixed for a given hardware+mode, and thus are not discoverable. However, I wouldn't be surprised if there are DRM-properties that you can query for this information. I honestly don't know, though. You can try checking the `libgbm` / `libdrm` / `mesa` codebase for details, or maybe @fooishbar knows more?

**Comment by fooishbar** [comment]
There's no per-mode discovery since format and mode are usually independent. However you can look at the formats array in `drmModePlaneInfo`, or parse the `IN_FORMATS` plane-property blob. drm_info/Weston/etc are probably your best places to look at for this.

**Comment by dvdhrm** [comment]
Thanks a lot for the info! I think the `IN_FORMATS` is suitable for this!
