### ISSUE TITLE
cannot set CRTC for connector 42 (22): Invalid argument

### ISSUE THREAD

**Issue by ooobsidian** [dvdhrm/docs#16]
Hi, @dvdhrm . When I run `modeset.c` on my board, the printed information is as follows:

```
using card '/dev/dri/card0'
mode for connector 42 is 1920x1080
cannot set CRTC for connector 42 (22): Invalid argument
exiting
```

This means that there is a problem on [line 571](https://github.com/dvdhrm/docs/blob/815de035b291cfdf3c858d4420482ffa42c878a1/drm-howto/modeset.c#L571C13-L571C13). Could you please help solve it?

**Comment by dvdhrm** [comment]
Do you run it on an embedded board? They often reject the 32bpp we pick. Give the modeset-atomic.c a try, if you can.
