### ISSUE TITLE
CRT problems 

### ISSUE THREAD

**Issue by peewe** [dvdhrm/docs#3]
Hey @dvdhrm,
I'm try to run this amazing project and my output is :
```
root@MY-VirtualBox:/home/MY/Desktop/docs-master/drm-howto# ./modeset-vsyncusing card '/dev/dri/card0'
mode for connector 26 is 1920x1080
cannot set CRTC for connector 26 (13): Permission denied
cannot flip CRTC for connector 26 (13): Permission denied
wait for pending page-flip to complete...
exiting

```
I wonder if there is a way to make it work on the new screens we have today ( not only on CRTC ).
Thank you for sharing your knowledge!

**Comment by dvdhrm** [comment]
You need to run this as root.

**Comment by peewe** [comment]
I run it as root and it works only in the terminal ( Ctrl+Alt+F1 ) there is a way to make it work in the windowing server?

**Comment by dvdhrm** [comment]
Only one client can access the graphics devices at a time. If you currently run a graphics server, it will have exclusive access. Hence, no, you cannot run those examples from a windowing server.
